"""init

Revision ID: c754f13ba539
Revises:
Create Date: 2025-12-02 11:10:52.576372

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c754f13ba539"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # create schemas
    op.execute("CREATE SCHEMA IF NOT EXISTS account;")
    op.execute("CREATE SCHEMA IF NOT EXISTS communication;")
    op.execute("CREATE SCHEMA IF NOT EXISTS partner_request;")
    op.execute("CREATE SCHEMA IF NOT EXISTS public;")
    op.execute("CREATE SCHEMA IF NOT EXISTS split_bill;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "base_profile",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nickname", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("avatar", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("wallpaper", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("bio", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("gender", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mbti", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("age_range", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="account",
    )
    op.create_table(
        "config",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("public_profile_fields", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="account",
    )
    op.create_table(
        "geo_profile",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workplace", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("residence", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="account",
    )
    op.create_table(
        "list",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("favorited_prs", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="account",
    )
    op.create_table(
        "wxmp",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("weixin_mp_openid", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("weixin_sa_openid", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("weixin_unionid", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="account",
    )
    op.create_table(
        "chat",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("avatar", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("parent", sa.Integer(), nullable=True),
        sa.Column("members", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="communication",
    )
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chat", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("viewed", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("forwarded_from", sa.Integer(), nullable=True),
        sa.Column("replied_to", sa.Integer(), nullable=True),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="communication",
    )
    op.create_table(
        "application",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("partner_request", sa.Integer(), nullable=False),
        sa.Column("applicant", sa.TEXT(), nullable=False),
        sa.Column("chat", sa.Integer(), nullable=False),
        sa.Column("eclose_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sub_applications", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="partner_request",
    )
    op.create_table(
        "base",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("chat", sa.Integer(), nullable=True),
        sa.Column("contract", sa.Integer(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("introduction", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="partner_request",
    )
    op.create_table(
        "partner",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("partner_request", sa.Integer(), nullable=False),
        sa.Column("role", sa.Integer(), nullable=False),
        sa.Column("player", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("history", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="partner_request",
    )
    op.create_table(
        "location",
        sa.Column("id", sa.TEXT(), nullable=False),
        sa.Column("friendly_address", sa.String(length=64), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_table(
        "contribution",
        sa.Column("split_bill", sa.Integer(), nullable=False),
        sa.Column("contributor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("relative_amount", sa.Float(), nullable=True),
        sa.Column("absolute_amount", sa.Integer(), nullable=True),
        sa.Column("contributed_amount", sa.Integer(), nullable=True),
        sa.Column("auto_deducted", sa.Boolean(), nullable=True),
        sa.Column("contributed_on_platform", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("contributed_on_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("split_bill", "contributor"),
        schema="split_bill",
    )
    op.create_table(
        "split_bill",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("partner_request", sa.Integer(), nullable=True),
        sa.Column("sub_split_bill", sa.Integer(), nullable=True),
        sa.Column("cancelled_for", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("details", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("proof", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=True),
        sa.Column("estimate_amount", sa.Integer(), nullable=True),
        sa.Column("payee", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("payer", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("contribute_before", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="split_bill",
    )
    op.create_table(
        "commute",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("route", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("trip_preference", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("on_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("off_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("workdays", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ride_hailing_orders", sa.ARRAY(sa.Integer()), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"], ["partner_request.base.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="partner_request",
    )
    op.create_table(
        "ride_hailing",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("route", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("trip_preference", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "ride_hailing_preference", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("ride_hailing_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"], ["partner_request.base.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="partner_request",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ride_hailing", schema="partner_request")
    op.drop_table("commute", schema="partner_request")
    op.drop_table("split_bill", schema="split_bill")
    op.drop_table("contribution", schema="split_bill")
    op.drop_table("location", schema="public")
    op.drop_table("partner", schema="partner_request")
    op.drop_table("base", schema="partner_request")
    op.drop_table("application", schema="partner_request")
    op.drop_table("message", schema="communication")
    op.drop_table("chat", schema="communication")
    op.drop_table("wxmp", schema="account")
    op.drop_table("list", schema="account")
    op.drop_table("geo_profile", schema="account")
    op.drop_table("config", schema="account")
    op.drop_table("base_profile", schema="account")
    # ### end Alembic commands ###

    # remove schemas
    op.execute("DROP SCHEMA IF EXISTS split_bill CASCADE;")
    op.execute("DROP SCHEMA IF EXISTS public CASCADE;")
    op.execute("DROP SCHEMA IF EXISTS partner_request CASCADE;")
    op.execute("DROP SCHEMA IF EXISTS communication CASCADE;")
    op.execute("DROP SCHEMA IF EXISTS account CASCADE;")
